pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:migroch/gadget-sidm.git
          - cd gadget-sidm.git
          - git push --mirror git@github.com:migroch/gadget-sidm.git