GADGET-2: accel.c File Reference
accel.c File Reference
driver routine to carry out force computation
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include "allvars.h"
#include "proto.h"
Functions
void compute_accelerations (int mode)
Detailed Description
driver routine to carry out force computation
Definition in file accel.c.
Function Documentation
void compute_accelerations (int mode)
This routine computes the accelerations for all active particles. First, the long-range PM force is computed if the TreePM algorithm is used and a "big" PM step is done. Next, the gravitational tree forces are computed. This also constructs the tree, if needed.
If gas particles are present, the density-loop for active SPH particles is carried out. This includes an iteration on the correct number of neighbours. Finally, the hydrodynamical forces are added.
Definition at line 24 of file accel.c.
References All, global_data_all_processes::CPU_Gravity, global_data_all_processes::CPU_Hydro, global_data_all_processes::CPU_PM, global_data_all_processes::CPU_Predict, density(), force_update_hmax(), gravity_forcetest(), gravity_tree(), hydro_force(), long_range_force(), global_data_all_processes::PM_Ti_endstep, second(), ThisTask, global_data_all_processes::Ti_Current, timediff(), global_data_all_processes::TotN_gas, and global_data_all_processes::TypeOfOpeningCriterion.
Referenced by run().
{
  double tstart, tend;
  if(ThisTask == 0)
    {
      printf("Start force computation...\n");
      fflush(stdout);
    }
#ifdef PMGRID
  if(All.PM_Ti_endstep == All.Ti_Current)
    {
      tstart = second();
      long_range_force();
      tend = second();
      All.CPU_PM += timediff(tstart, tend);
    }
#endif
  tstart = second();            /* measure the time for the full force computation */
  gravity_tree();               /* computes gravity accel. */
  if(All.TypeOfOpeningCriterion == 1 && All.Ti_Current == 0)
    gravity_tree();             /* For the first timestep, we redo it
                                 * to allow usage of relative opening
                                 * criterion for consistent accuracy.
                                 */
  tend = second();
  All.CPU_Gravity += timediff(tstart, tend);
#ifdef FORCETEST
  gravity_forcetest();
#endif
  if(All.TotN_gas > 0)
    {
      if(ThisTask == 0)
        {
          printf("Start density computation...\n");
          fflush(stdout);
        }
      tstart = second();
      density();                /* computes density, and pressure */
      tend = second();
      All.CPU_Hydro += timediff(tstart, tend);
      tstart = second();
      force_update_hmax();      /* tell the tree nodes the new SPH smoothing length such that they are guaranteed to hold the correct max(Hsml) */
      tend = second();
      All.CPU_Predict += timediff(tstart, tend);
      if(ThisTask == 0)
        {
          printf("Start hydro-force computation...\n");
          fflush(stdout);
        }
      tstart = second();
      hydro_force();            /* adds hydrodynamical accelerations and computes viscous entropy injection  */
      tend = second();
      All.CPU_Hydro += timediff(tstart, tend);
    }
  if(ThisTask == 0)
    {
      printf("force computation done.\n");
      fflush(stdout);
    }
}