GADGET-2: driftfac.c File Reference
driftfac.c File Reference
compute loop-up tables for prefactors in cosmological integration
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_integration.h>
#include "allvars.h"
#include "proto.h"
Defines
#define WORKSIZE 100000
Functions
void init_drift_table (void)
double get_drift_factor (int time0, int time1)
double get_gravkick_factor (int time0, int time1)
double get_hydrokick_factor (int time0, int time1)
double drift_integ (double a, void *param)
double gravkick_integ (double a, void *param)
double hydrokick_integ (double a, void *param)
double growthfactor_integ (double a, void *param)
Variables
static double logTimeBegin
static double logTimeMax
Detailed Description
compute loop-up tables for prefactors in cosmological integration
Definition in file driftfac.c.
Define Documentation
#define WORKSIZE 100000
Referenced by init_drift_table().
Function Documentation
double drift_integ (double a, void * param)
Integration kernel for drift factor computation.
Definition at line 179 of file driftfac.c.
References All, global_data_all_processes::Hubble, global_data_all_processes::Omega0, and global_data_all_processes::OmegaLambda.
{
  double h;
  h = All.Omega0 / (a * a * a) + (1 - All.Omega0 - All.OmegaLambda) / (a * a) + All.OmegaLambda;
  h = All.Hubble * sqrt(h);
  return 1 / (h * a * a * a);
}
double get_drift_factor (int time0, int time1)
This function integrates the cosmological prefactor for a drift step between time0 and time1. The value returned is *
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
Definition at line 67 of file driftfac.c.
References All, DRIFT_TABLE_LENGTH, DriftTable, logTimeBegin, logTimeMax, and global_data_all_processes::Timebase_interval.
Referenced by move_particles().
{
  double a1, a2, df1, df2, u1, u2;
  int i1, i2;
  /* note: will only be called for cosmological integration */
  a1 = logTimeBegin + time0 * All.Timebase_interval;
  a2 = logTimeBegin + time1 * All.Timebase_interval;
  u1 = (a1 - logTimeBegin) / (logTimeMax - logTimeBegin) * DRIFT_TABLE_LENGTH;
  i1 = (int) u1;
  if(i1 >= DRIFT_TABLE_LENGTH)
    i1 = DRIFT_TABLE_LENGTH - 1;
  if(i1 <= 1)
    df1 = u1 * DriftTable[0];
  else
    df1 = DriftTable[i1 - 1] + (DriftTable[i1] - DriftTable[i1 - 1]) * (u1 - i1);
  u2 = (a2 - logTimeBegin) / (logTimeMax - logTimeBegin) * DRIFT_TABLE_LENGTH;
  i2 = (int) u2;
  if(i2 >= DRIFT_TABLE_LENGTH)
    i2 = DRIFT_TABLE_LENGTH - 1;
  if(i2 <= 1)
    df2 = u2 * DriftTable[0];
  else
    df2 = DriftTable[i2 - 1] + (DriftTable[i2] - DriftTable[i2 - 1]) * (u2 - i2);
  return df2 - df1;
}
double get_gravkick_factor (int time0, int time1)
This function integrates the cosmological prefactor for a kick step of the gravitational force.
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
Definition at line 105 of file driftfac.c.
References All, DRIFT_TABLE_LENGTH, GravKickTable, logTimeBegin, logTimeMax, and global_data_all_processes::Timebase_interval.
Referenced by advance_and_find_timesteps(), compute_global_quantities_of_system(), fill_write_buffer(), and move_particles().
{
  double a1, a2, df1, df2, u1, u2;
  int i1, i2;
  /* note: will only be called for cosmological integration */
  a1 = logTimeBegin + time0 * All.Timebase_interval;
  a2 = logTimeBegin + time1 * All.Timebase_interval;
  u1 = (a1 - logTimeBegin) / (logTimeMax - logTimeBegin) * DRIFT_TABLE_LENGTH;
  i1 = (int) u1;
  if(i1 >= DRIFT_TABLE_LENGTH)
    i1 = DRIFT_TABLE_LENGTH - 1;
  if(i1 <= 1)
    df1 = u1 * GravKickTable[0];
  else
    df1 = GravKickTable[i1 - 1] + (GravKickTable[i1] - GravKickTable[i1 - 1]) * (u1 - i1);
  u2 = (a2 - logTimeBegin) / (logTimeMax - logTimeBegin) * DRIFT_TABLE_LENGTH;
  i2 = (int) u2;
  if(i2 >= DRIFT_TABLE_LENGTH)
    i2 = DRIFT_TABLE_LENGTH - 1;
  if(i2 <= 1)
    df2 = u2 * GravKickTable[0];
  else
    df2 = GravKickTable[i2 - 1] + (GravKickTable[i2] - GravKickTable[i2 - 1]) * (u2 - i2);
  return df2 - df1;
}
double get_hydrokick_factor (int time0, int time1)
This function integrates the cosmological prefactor for a kick step of the hydrodynamical force.
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
Definition at line 142 of file driftfac.c.
References All, DRIFT_TABLE_LENGTH, HydroKickTable, logTimeBegin, logTimeMax, and global_data_all_processes::Timebase_interval.
Referenced by advance_and_find_timesteps(), compute_global_quantities_of_system(), fill_write_buffer(), and move_particles().
{
  double a1, a2, df1, df2, u1, u2;
  int i1, i2;
  /* note: will only be called for cosmological integration */
  a1 = logTimeBegin + time0 * All.Timebase_interval;
  a2 = logTimeBegin + time1 * All.Timebase_interval;
  u1 = (a1 - logTimeBegin) / (logTimeMax - logTimeBegin) * DRIFT_TABLE_LENGTH;
  i1 = (int) u1;
  if(i1 >= DRIFT_TABLE_LENGTH)
    i1 = DRIFT_TABLE_LENGTH - 1;
  if(i1 <= 1)
    df1 = u1 * HydroKickTable[0];
  else
    df1 = HydroKickTable[i1 - 1] + (HydroKickTable[i1] - HydroKickTable[i1 - 1]) * (u1 - i1);
  u2 = (a2 - logTimeBegin) / (logTimeMax - logTimeBegin) * DRIFT_TABLE_LENGTH;
  i2 = (int) u2;
  if(i2 >= DRIFT_TABLE_LENGTH)
    i2 = DRIFT_TABLE_LENGTH - 1;
  if(i2 <= 1)
    df2 = u2 * HydroKickTable[0];
  else
    df2 = HydroKickTable[i2 - 1] + (HydroKickTable[i2] - HydroKickTable[i2 - 1]) * (u2 - i2);
  return df2 - df1;
}
double gravkick_integ (double a, void * param)
Integration kernel for gravitational kick factor computation.
Definition at line 191 of file driftfac.c.
References All, global_data_all_processes::Hubble, global_data_all_processes::Omega0, and global_data_all_processes::OmegaLambda.
{
  double h;
  h = All.Omega0 / (a * a * a) + (1 - All.Omega0 - All.OmegaLambda) / (a * a) + All.OmegaLambda;
  h = All.Hubble * sqrt(h);
  return 1 / (h * a * a);
}
double growthfactor_integ (double a, void * param)
Definition at line 214 of file driftfac.c.
References All, global_data_all_processes::Omega0, global_data_all_processes::OmegaLambda, and pow().
{
  double s;
  s = All.Omega0 + (1 - All.Omega0 - All.OmegaLambda) * a + All.OmegaLambda * a * a * a;
  s = sqrt(s);
  return pow(sqrt(a) / s, 3);
}
double hydrokick_integ (double a, void * param)
Integration kernel for hydrodynamical kick factor computation.
< adiabatic index of simulated gas
Definition at line 204 of file driftfac.c.
References All, GAMMA_MINUS1, global_data_all_processes::Hubble, global_data_all_processes::Omega0, global_data_all_processes::OmegaLambda, and pow().
{
  double h;
  h = All.Omega0 / (a * a * a) + (1 - All.Omega0 - All.OmegaLambda) / (a * a) + All.OmegaLambda;
  h = All.Hubble * sqrt(h);
  return 1 / (h * pow(a, 3 * GAMMA_MINUS1) * a);
}
void init_drift_table (void)
This function computes look-up tables for factors needed in cosmological integrations. The (simple) integrations are carried out with the GSL library. Separate factors are computed for the "drift", and the gravitational and hydrodynamical "kicks". The lookup-table is used for reasons of speed.
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
< length of the lookup table used to hold the drift and kick factors
Definition at line 26 of file driftfac.c.
References All, DriftTable, GravKickTable, HydroKickTable, logTimeBegin, logTimeMax, global_data_all_processes::TimeBegin, global_data_all_processes::TimeMax, WORKSIZE, and workspace.
Referenced by begrun().
{
#define WORKSIZE 100000
  int i;
  double result, abserr;
  gsl_function F;
  gsl_integration_workspace *workspace;
  logTimeBegin = log(All.TimeBegin);
  logTimeMax = log(All.TimeMax);
  workspace = gsl_integration_workspace_alloc(WORKSIZE);
  for(i = 0; i < DRIFT_TABLE_LENGTH; i++)
    {
      F.function = &drift_integ;
      gsl_integration_qag(&F, exp(logTimeBegin), exp(logTimeBegin + ((logTimeMax - logTimeBegin) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
                          1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
      DriftTable[i] = result;
      F.function = &gravkick_integ;
      gsl_integration_qag(&F, exp(logTimeBegin), exp(logTimeBegin + ((logTimeMax - logTimeBegin) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
                          1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
      GravKickTable[i] = result;
      F.function = &hydrokick_integ;
      gsl_integration_qag(&F, exp(logTimeBegin), exp(logTimeBegin + ((logTimeMax - logTimeBegin) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
                          1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
      HydroKickTable[i] = result;
    }
  gsl_integration_workspace_free(workspace);
}
Variable Documentation
double logTimeBegin [static]
Definition at line 16 of file driftfac.c.
Referenced by get_drift_factor(), get_gravkick_factor(), get_hydrokick_factor(), and init_drift_table().
double logTimeMax [static]
Definition at line 17 of file driftfac.c.
Referenced by get_drift_factor(), get_gravkick_factor(), get_hydrokick_factor(), and init_drift_table().