gadget-sidm: endrun.c File Reference
endrun.c File Reference
Termination of simulation.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include <signal.h>
#include <unistd.h>
#include "allvars.h"
#include "proto.h"
Functions
void endrun (int ierr)
Detailed Description
Termination of simulation.
This file contains routines for termination of the simulation.
Definition in file endrun.c.
Function Documentation
void endrun (int ierr)
This function aborts the simulations. If a single processors wants an immediate termination, the function needs to be called with ierr>0. A bunch of MPI-error messages may also appear in this case. For ierr=0, MPI is gracefully cleaned up, but this requires that all processors call endrun().
Definition at line 25 of file endrun.c.
References terminate_processes(), and ThisTask.
Referenced by allocate_commbuffers(), allocate_memory(), AllocateInteractionTable(), check_omega(), compute_potential(), density(), domain_decompose(), domain_exchangeParticles(), domain_topsplit(), domain_topsplit_local(), find_files(), find_next_outputtime(), force_create_empty_nodes(), force_insert_pseudo_particles(), force_treeallocate(), force_treebuild_single(), force_treeevaluate(), force_treeevaluate_potential(), force_treeevaluate_potential_shortrange(), force_treeevaluate_shortrange(), get_particles_in_block(), get_timestep(), gravity_forcetest(), init(), long_range_force(), main(), my_fread(), my_fwrite(), ngb_treeallocate(), open_outputfiles(), pm_init_periodic_allocate(), read_file(), read_parameter_file(), readjust_timebase(), restart(), savepositions(), update_interaction_table(), and write_file().
{
  if(ierr)
    {
      printf("task %d: endrun called with an error level of %d\n\n\n", ThisTask, ierr);
      fflush(stdout);
#ifdef DEBUG
      terminate_processes();
      raise(SIGABRT);
      sleep(60);
#else
      MPI_Abort(MPI_COMM_WORLD, ierr);
#endif
      exit(0);
    }
  MPI_Finalize();
  exit(0);
}