GADGET-2: init.c File Reference
init.c File Reference
Code for initialisation of a simulation from initial conditions.
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include "allvars.h"
#include "proto.h"
Functions
void init (void)
void check_omega (void)
void setup_smoothinglengths (void)
Detailed Description
Code for initialisation of a simulation from initial conditions.
Definition in file init.c.
Function Documentation
void check_omega (void)
This routine computes the mass content of the box and compares it to the specified value of Omega-matter. If discrepant, the run is terminated.
Definition at line 161 of file init.c.
References All, global_data_all_processes::BoxSize, endrun(), global_data_all_processes::G, global_data_all_processes::Hubble, state_of_system::Mass, NumPart, global_data_all_processes::Omega0, P, and ThisTask.
Referenced by init().
{
  double mass = 0, masstot, omega;
  int i;
  for(i = 0; i < NumPart; i++)
    mass += P[i].Mass;
  MPI_Allreduce(&mass, &masstot, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
  omega =
    masstot / (All.BoxSize * All.BoxSize * All.BoxSize) / (3 * All.Hubble * All.Hubble / (8 * M_PI * All.G));
  if(fabs(omega - All.Omega0) > 1.0e-3)
    {
      if(ThisTask == 0)
        {
          printf("\n\nI've found something odd!\n");
          printf
            ("The mass content accounts only for Omega=%g,\nbut you specified Omega=%g in the parameterfile.\n",
             omega, All.Omega0);
          printf("\nI better stop.\n");
          fflush(stdout);
        }
      endrun(1);
    }
}
void init (void)
This function reads the initial conditions, and allocates storage for the tree. Various variables of the particle data are initialised and An intial domain decomposition is performed. If SPH particles are present, the inial SPH smoothing lengths are determined.
< The simulated timespan is mapped onto the integer interval [0,TIMESPAN], * where TIMESPAN needs to be a power of 2. Note that (1<<28) corresponds to 2^29
< The simulated timespan is mapped onto the integer interval [0,TIMESPAN], * where TIMESPAN needs to be a power of 2. Note that (1<<28) corresponds to 2^29
< defines maximum length of neighbour list
< adiabatic index of simulated gas
< adiabatic index of simulated gas
Definition at line 20 of file init.c.
References All, check_omega(), global_data_all_processes::ComovingIntegrationOn, sph_particle_data::Density, domain_Decomposition(), sph_particle_data::DtEntropy, endrun(), io_header::flag_entropy_instead_u, Flag_FullStep, force_treeallocate(), GAMMA_MINUS1, get_random_number(), particle_data::GravCost, header, sph_particle_data::Hsml, sph_particle_data::HydroAccel, global_data_all_processes::ICFormat, global_data_all_processes::InitCondFile, MAX_NGB, global_data_all_processes::MaxPart, N_gas, ngb_treeallocate(), ngb_treebuild(), global_data_all_processes::NumCurrentTiStep, global_data_all_processes::NumForcesSinceLastDomainDecomp, NumPart, particle_data::OldAcc, P, global_data_all_processes::PeriodicBoundariesOn, global_data_all_processes::PM_Ti_begstep, global_data_all_processes::PM_Ti_endstep, particle_data::Potential, pow(), read_ic(), RestartFlag, seed_glass(), set_softenings(), setup_smoothinglengths(), global_data_all_processes::SnapshotFileCount, SphP, ThisTask, particle_data::Ti_begstep, global_data_all_processes::Ti_Current, particle_data::Ti_endstep, global_data_all_processes::Time, TIMEBASE, global_data_all_processes::Timebase_interval, global_data_all_processes::TimeBegin, global_data_all_processes::TimeBetStatistics, global_data_all_processes::TimeLastStatistics, global_data_all_processes::TimeMax, global_data_all_processes::TotNumOfForces, global_data_all_processes::TotNumPart, global_data_all_processes::TreeAllocFactor, global_data_all_processes::TreeDomainUpdateFrequency, TreeReconstructFlag, particle_data::Vel, and sph_particle_data::VelPred.
Referenced by begrun().
{
  int i, j;
  double a3;
  All.Time = All.TimeBegin;
  switch (All.ICFormat)
    {
    case 1:
#if (MAKEGLASS > 1)
      seed_glass();
#else
      read_ic(All.InitCondFile);
#endif
      break;
    case 2:
    case 3:
      read_ic(All.InitCondFile);
      break;
    default:
      if(ThisTask == 0)
        printf("ICFormat=%d not supported.\n", All.ICFormat);
      endrun(0);
    }
  All.Time = All.TimeBegin;
  All.Ti_Current = 0;
  if(All.ComovingIntegrationOn)
    {
      All.Timebase_interval = (log(All.TimeMax) - log(All.TimeBegin)) / TIMEBASE;
      a3 = All.Time * All.Time * All.Time;
    }
  else
    {
      All.Timebase_interval = (All.TimeMax - All.TimeBegin) / TIMEBASE;
      a3 = 1;
    }
  set_softenings();
  All.NumCurrentTiStep = 0;     /* setup some counters */
  All.SnapshotFileCount = 0;
  if(RestartFlag == 2)
    All.SnapshotFileCount = atoi(All.InitCondFile + strlen(All.InitCondFile) - 3) + 1;
  All.TotNumOfForces = 0;
  All.NumForcesSinceLastDomainDecomp = 0;
  if(All.ComovingIntegrationOn)
    if(All.PeriodicBoundariesOn == 1)
      check_omega();
  All.TimeLastStatistics = All.TimeBegin - All.TimeBetStatistics;
  if(All.ComovingIntegrationOn) /*  change to new velocity variable */
    {
      for(i = 0; i < NumPart; i++)
        for(j = 0; j < 3; j++)
          P[i].Vel[j] *= sqrt(All.Time) * All.Time;
    }
  for(i = 0; i < NumPart; i++)  /*  start-up initialization */
    {
      for(j = 0; j < 3; j++)
        P[i].GravAccel[j] = 0;
#ifdef PMGRID
      for(j = 0; j < 3; j++)
        P[i].GravPM[j] = 0;
#endif
      P[i].Ti_endstep = 0;
      P[i].Ti_begstep = 0;
      P[i].OldAcc = 0;
      P[i].GravCost = 1;
      P[i].Potential = 0;
    }
#ifdef PMGRID
  All.PM_Ti_endstep = All.PM_Ti_begstep = 0;
#endif
#ifdef FLEXSTEPS
  All.PresentMinStep = TIMEBASE;
  for(i = 0; i < NumPart; i++)  /*  start-up initialization */
    {
      P[i].FlexStepGrp = (int) (TIMEBASE * get_random_number(P[i].ID));
    }
#endif
  for(i = 0; i < N_gas; i++)    /* initialize sph_properties */
    {
      for(j = 0; j < 3; j++)
        {
          SphP[i].VelPred[j] = P[i].Vel[j];
          SphP[i].HydroAccel[j] = 0;
        }
      SphP[i].DtEntropy = 0;
      if(RestartFlag == 0)
        {
          SphP[i].Hsml = 0;
          SphP[i].Density = -1;
        }
    }
  ngb_treeallocate(MAX_NGB);
  force_treeallocate(All.TreeAllocFactor * All.MaxPart, All.MaxPart);
  All.NumForcesSinceLastDomainDecomp = 1 + All.TotNumPart * All.TreeDomainUpdateFrequency;
  Flag_FullStep = 1;            /* to ensure that Peano-Hilber order is done */
  domain_Decomposition();       /* do initial domain decomposition (gives equal numbers of particles) */
  ngb_treebuild();              /* will build tree */
  setup_smoothinglengths();
  TreeReconstructFlag = 1;
  /* at this point, the entropy variable normally contains the
   * internal energy, read in from the initial conditions file, unless the file
   * explicitly signals that the initial conditions contain the entropy directly.
   * Once the density has been computed, we can convert thermal energy to entropy.
   */
#ifndef ISOTHERM_EQS
  if(header.flag_entropy_instead_u == 0)
    for(i = 0; i < N_gas; i++)
      SphP[i].Entropy = GAMMA_MINUS1 * SphP[i].Entropy / pow(SphP[i].Density / a3, GAMMA_MINUS1);
#endif
}
void setup_smoothinglengths (void)
This function is used to find an initial smoothing length for each SPH particle. It guarantees that the number of neighbours will be between desired_ngb-MAXDEV and desired_ngb+MAXDEV. For simplicity, a first guess of the smoothing length is provided to the function density(), which will then iterate if needed to find the right smoothing length.
Definition at line 198 of file init.c.
References All, NODE::d, density(), global_data_all_processes::DesNumNgb, Father, sph_particle_data::Hsml, NODE::len, particle_data::Mass, N_gas, Nodes, P, pow(), RestartFlag, SphP, and NODE::u.
Referenced by init().
{
  int i, no, p;
  if(RestartFlag == 0)
    {
      for(i = 0; i < N_gas; i++)
        {
          no = Father[i];
          while(10 * All.DesNumNgb * P[i].Mass > Nodes[no].u.d.mass)
            {
              p = Nodes[no].u.d.father;
              if(p < 0)
                break;
              no = p;
            }
#ifndef TWODIMS
          SphP[i].Hsml =
            pow(3.0 / (4 * M_PI) * All.DesNumNgb * P[i].Mass / Nodes[no].u.d.mass, 1.0 / 3) * Nodes[no].len;
#else
          SphP[i].Hsml =
            pow(1.0 / (M_PI) * All.DesNumNgb * P[i].Mass / Nodes[no].u.d.mass, 1.0 / 2) * Nodes[no].len;
#endif
        }
    }
  density();
}