GADGET-2: longrange.c File Reference
longrange.c File Reference
driver routines for computation of long-range gravitational PM force
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include "allvars.h"
#include "proto.h"
Functions
void long_range_init (void)
void long_range_init_regionsize (void)
void long_range_force (void)
Detailed Description
driver routines for computation of long-range gravitational PM force
Definition in file longrange.c.
Function Documentation
void long_range_force (void)
This function is a driver routine for the long-range PM force computation. It calls periodic and/or non-periodic FFT routines as needed for the present simulation set-up.
Definition at line 56 of file longrange.c.
References All, global_data_all_processes::ComovingIntegrationOn, endrun(), global_data_all_processes::Hubble, NumPart, global_data_all_processes::Omega0, global_data_all_processes::OmegaLambda, P, pm_init_regionsize(), pm_setup_nonperiodic_kernel(), pmforce_nonperiodic(), and pmforce_periodic().
Referenced by compute_accelerations().
{
  int i;
#ifndef PERIODIC
  int j;
  double fac;
#endif
  for(i = 0; i < NumPart; i++)
    P[i].GravPM[0] = P[i].GravPM[1] = P[i].GravPM[2] = 0;
#ifdef NOGRAVITY
  return;
#endif
#ifdef PERIODIC
  pmforce_periodic();
#ifdef PLACEHIGHRESREGION
  i = pmforce_nonperiodic(1);
  if(i == 1)                    /* this is returned if a particle lied outside allowed range */
    {
      pm_init_regionsize();
      pm_setup_nonperiodic_kernel();
      i = pmforce_nonperiodic(1);       /* try again */
    }
  if(i == 1)
    endrun(68686);
#endif
#else
  i = pmforce_nonperiodic(0);
  if(i == 1)                    /* this is returned if a particle lied outside allowed range */
    {
      pm_init_regionsize();
      pm_setup_nonperiodic_kernel();
      i = pmforce_nonperiodic(0);       /* try again */
    }
  if(i == 1)
    endrun(68687);
#ifdef PLACEHIGHRESREGION
  i = pmforce_nonperiodic(1);
  if(i == 1)                    /* this is returned if a particle lied outside allowed range */
    {
      pm_init_regionsize();
      pm_setup_nonperiodic_kernel();
      /* try again */
      for(i = 0; i < NumPart; i++)
        P[i].GravPM[0] = P[i].GravPM[1] = P[i].GravPM[2] = 0;
      i = pmforce_nonperiodic(0) + pmforce_nonperiodic(1);
    }
  if(i != 0)
    endrun(68688);
#endif
#endif
#ifndef PERIODIC
  if(All.ComovingIntegrationOn)
    {
      fac = 0.5 * All.Hubble * All.Hubble * All.Omega0;
      for(i = 0; i < NumPart; i++)
        for(j = 0; j < 3; j++)
          P[i].GravPM[j] += fac * P[i].Pos[j];
    }
  /* Finally, the following factor allows a computation of cosmological simulation
     with vacuum energy in physical coordinates */
  if(All.ComovingIntegrationOn == 0)
    {
      fac = All.OmegaLambda * All.Hubble * All.Hubble;
      for(i = 0; i < NumPart; i++)
        for(j = 0; j < 3; j++)
          P[i].GravPM[j] += fac * P[i].Pos[j];
    }
#endif
}
void long_range_init (void)
Calls initializiation routines of periodic or/and non-periodic FFT routines.
Definition at line 20 of file longrange.c.
References pm_init_nonperiodic(), and pm_init_periodic().
Referenced by begrun().
{
#ifdef PERIODIC
  pm_init_periodic();
#ifdef PLACEHIGHRESREGION
  pm_init_nonperiodic();
#endif
#else
  pm_init_nonperiodic();
#endif
}
void long_range_init_regionsize (void)
This function calls subroutines that determine the spatial region covered by the PM mesh.
Definition at line 36 of file longrange.c.
References pm_init_regionsize(), pm_setup_nonperiodic_kernel(), and RestartFlag.
Referenced by begrun().
{
#ifdef PERIODIC
#ifdef PLACEHIGHRESREGION
  if(RestartFlag != 1)
    pm_init_regionsize();
  pm_setup_nonperiodic_kernel();
#endif
#else
  if(RestartFlag != 1)
    pm_init_regionsize();
  pm_setup_nonperiodic_kernel();
#endif
}