GADGET-2: predict.c File Reference
predict.c File Reference
drift particles by a small time interval
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include <gsl/gsl_math.h>
#include "allvars.h"
#include "proto.h"
Functions
void move_particles (int time0, int time1)
void do_box_wrapping (void)
Detailed Description
drift particles by a small time interval
This function contains code to implement a drift operation on all the particles, which represents one part of the leapfrog integration scheme.
Definition in file predict.c.
Function Documentation
void do_box_wrapping (void)
This function makes sure that all particle coordinates (Pos) are periodically mapped onto the interval [0, BoxSize]. After this function has been called, a new domain decomposition should be done, which will also force a new tree construction.
Definition at line 103 of file predict.c.
References All, global_data_all_processes::BoxSize, NumPart, P, and particle_data::Pos.
Referenced by domain_Decomposition().
{
  int i, j;
  double boxsize[3];
  for(j = 0; j < 3; j++)
    boxsize[j] = All.BoxSize;
#ifdef LONG_X
  boxsize[0] *= LONG_X;
#endif
#ifdef LONG_Y
  boxsize[1] *= LONG_Y;
#endif
#ifdef LONG_Z
  boxsize[2] *= LONG_Z;
#endif
  for(i = 0; i < NumPart; i++)
    for(j = 0; j < 3; j++)
      {
        while(P[i].Pos[j] < 0)
          P[i].Pos[j] += boxsize[j];
        while(P[i].Pos[j] >= boxsize[j])
          P[i].Pos[j] -= boxsize[j];
      }
}
void move_particles (int time0, int time1)
This function drifts all particles from the current time to the future: time0 - > time1
If there is no explicit tree construction in the following timestep, the tree nodes are also drifted and updated accordingly. Note: For periodic boundary conditions, the mapping of coordinates onto the interval [0,All.BoxSize] is only done before the domain decomposition, or for outputs to snapshot files. This simplifies dynamic tree updates, and allows the domain decomposition to be carried out only every once in a while.
< adiabatic index of simulated gas
Definition at line 31 of file predict.c.
References All, global_data_all_processes::ComovingIntegrationOn, global_data_all_processes::CPU_Predict, NODE::d, sph_particle_data::Density, sph_particle_data::DtEntropy, sph_particle_data::Entropy, Extnodes, force_update_len(), force_update_pseudoparticles(), GAMMA, get_drift_factor(), get_gravkick_factor(), get_hydrokick_factor(), particle_data::GravAccel, particle_data::GravPM, sph_particle_data::Hsml, sph_particle_data::HydroAccel, global_data_all_processes::MaxPart, global_data_all_processes::MinGasHsml, Nodes, global_data_all_processes::NumForcesSinceLastDomainDecomp, Numnodestree, NumPart, P, particle_data::Pos, pow(), sph_particle_data::Pressure, second(), SphP, particle_data::Ti_begstep, particle_data::Ti_endstep, global_data_all_processes::Timebase_interval, timediff(), global_data_all_processes::TotNumPart, global_data_all_processes::TreeDomainUpdateFrequency, particle_data::Type, NODE::u, particle_data::Vel, and extNODE::vs.
Referenced by find_next_sync_point_and_drift().
{
  int i, j;
  double dt_drift, dt_gravkick, dt_hydrokick, dt_entr;
  double t0, t1;
  t0 = second();
  if(All.ComovingIntegrationOn)
    {
      dt_drift = get_drift_factor(time0, time1);
      dt_gravkick = get_gravkick_factor(time0, time1);
      dt_hydrokick = get_hydrokick_factor(time0, time1);
    }
  else
    {
      dt_drift = dt_gravkick = dt_hydrokick = (time1 - time0) * All.Timebase_interval;
    }
  for(i = 0; i < NumPart; i++)
    {
      for(j = 0; j < 3; j++)
        P[i].Pos[j] += P[i].Vel[j] * dt_drift;
      if(P[i].Type == 0)
        {
#ifdef PMGRID
          for(j = 0; j < 3; j++)
            SphP[i].VelPred[j] +=
              (P[i].GravAccel[j] + P[i].GravPM[j]) * dt_gravkick + SphP[i].HydroAccel[j] * dt_hydrokick;
#else
          for(j = 0; j < 3; j++)
            SphP[i].VelPred[j] += P[i].GravAccel[j] * dt_gravkick + SphP[i].HydroAccel[j] * dt_hydrokick;
#endif
          SphP[i].Density *= exp(-SphP[i].DivVel * dt_drift);
          SphP[i].Hsml *= exp(0.333333333333 * SphP[i].DivVel * dt_drift);
          if(SphP[i].Hsml < All.MinGasHsml)
            SphP[i].Hsml = All.MinGasHsml;
          dt_entr = (time1 - (P[i].Ti_begstep + P[i].Ti_endstep) / 2) * All.Timebase_interval;
          SphP[i].Pressure = (SphP[i].Entropy + SphP[i].DtEntropy * dt_entr) * pow(SphP[i].Density, GAMMA);
        }
    }
  /* if domain-decomp and tree are not going to be reconstructed, update dynamically.  */
  if(All.NumForcesSinceLastDomainDecomp < All.TotNumPart * All.TreeDomainUpdateFrequency)
    {
      for(i = 0; i < Numnodestree; i++)
        for(j = 0; j < 3; j++)
          Nodes[All.MaxPart + i].u.d.s[j] += Extnodes[All.MaxPart + i].vs[j] * dt_drift;
      force_update_len();
      force_update_pseudoparticles();
    }
  t1 = second();
  All.CPU_Predict += timediff(t0, t1);
}