GADGET-2: system.c File Reference
system.c File Reference
contains miscellaneous routines, e.g. elapsed time measurements
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <unistd.h>
#include <signal.h>
#include <gsl/gsl_rng.h>
#include <mpi.h>
#include "allvars.h"
#include "proto.h"
Functions
double get_random_number (int id)
void set_random_numbers (void)
double second (void)
double timediff (double t0, double t1)
double dmax (double x, double y)
double dmin (double x, double y)
int imax (int x, int y)
int imin (int x, int y)
Detailed Description
contains miscellaneous routines, e.g. elapsed time measurements
Definition in file system.c.
Function Documentation
double dmax (double x, double y)
returns the maximum of two double
Definition at line 91 of file system.c.
Referenced by density(), domain_findSplit(), domain_shiftSplit(), fill_write_buffer(), force_treeevaluate_direct(), and read_ic().
{
  if(x > y)
    return x;
  else
    return y;
}
double dmin (double x, double y)
returns the minimum of two double
Definition at line 101 of file system.c.
Referenced by hydro_evaluate().
{
  if(x < y)
    return x;
  else
    return y;
}
double get_random_number (int id)
This routine returns a random number taken from a table of random numbers, which is refilled every timestep. This method is used to allow random number application to particles independent of the number of processors used, and independent of the particular order the particles have. In order to work properly, the particle IDs should be set properly to unique integer values.
< gives the length of a table with random numbers, refreshed at every timestep. This is used to allow application of random numbers to a specific particle in a way that is independent of the number of processors used.
Definition at line 29 of file system.c.
References RndTable.
Referenced by advance_and_find_timesteps(), force_treebuild_single(), force_treeevaluate(), force_treeevaluate_shortrange(), gravity_forcetest(), and init().
{
  return RndTable[(id % RNDTABLE)];
}
int imax (int x, int y)
returns the maximum of two integers
Definition at line 111 of file system.c.
Referenced by hydro_evaluate(), and pm_init_periodic_allocate().
{
  if(x > y)
    return x;
  else
    return y;
}
int imin (int x, int y)
returns the minimum of two integers
Definition at line 121 of file system.c.
Referenced by domain_findExchangeNumbers().
{
  if(x < y)
    return x;
  else
    return y;
}
double second (void)
returns the number of cpu-ticks in seconds that have elapsed, or the wall-clock time obtained with MPI_Wtime().
Definition at line 49 of file system.c.
Referenced by advance_and_find_timesteps(), compute_accelerations(), compute_potential(), density(), domain_Decomposition(), find_next_sync_point_and_drift(), gravity_forcetest(), gravity_tree(), hydro_force(), main(), move_particles(), run(), and savepositions().
{
#ifdef WALLCLOCK
  return MPI_Wtime();
#else
  return ((double) clock()) / CLOCKS_PER_SEC;
#endif
  /* note: on AIX and presumably many other 32bit systems,
   * clock() has only a resolution of 10ms=0.01sec
   */
}
void set_random_numbers (void)
This routine fills the random number table.
< gives the length of a table with random numbers, refreshed at every timestep. This is used to allow application of random numbers to a specific particle in a way that is independent of the number of processors used.
Definition at line 37 of file system.c.
References random_generator, and RndTable.
Referenced by begrun(), and every_timestep_stuff().
{
  int i;
  for(i = 0; i < RNDTABLE; i++)
    RndTable[i] = gsl_rng_uniform(random_generator);
}
double timediff (double t0, double t1)
returns the time difference between two measurements obtained with second(). The routine takes care of the possible overflow of the tick counter on 32bit systems, but depending on the system, this may not always work properly. Similarly, in some MPI implementations, the MPI_Wtime() function may also overflow, in which case a negative time difference would be returned. The routine returns instead a time difference equal to 0.
Definition at line 70 of file system.c.
References pow().
Referenced by advance_and_find_timesteps(), compute_accelerations(), compute_potential(), density(), domain_Decomposition(), find_next_sync_point_and_drift(), gravity_forcetest(), gravity_tree(), hydro_force(), main(), move_particles(), run(), and savepositions().
{
  double dt;
  dt = t1 - t0;
  if(dt < 0)    /* overflow has occured (for systems with 32bit tick counter) */
    {
#ifdef WALLCLOCK
      dt = 0;
#else
      dt = t1 + pow(2, 32) / CLOCKS_PER_SEC - t0;
#endif
    }
  return dt;
}